-- SELECT * FROM CUSTOMERS;
-- SELECT NAME FROM CUSTOMERS;
-- SELECT * FROM CUSTOMERS WHERE COUNTRY= "RWANDA";
-- SELECT * FROM EMPLOYEES WHERE SALARY>1000;
-- SELECT * FROM EMPLOYEES order by SALARY DESC;
-- SELECT * FROM CUSTOMERS ORDER BY NAME ASC;
-- SELECT * FROM CUSTOMERS ORDER BY NAME LIMIT 4;
-- SELECT DISTINCT COUNTRY FROM CUSTOMERS;
-- SELECT COUNT(COUNTRY) FROM CUSTOMERS;
-- SELECT MAX(SALARY) FROM EMPLOYEES;
-- SELECT  MIN(SALARY) FROM EMPLOYEES;
-- SELECT AVG(SALARY) FROM EMPLOYEES;
-- SELECT SUM(SALARY) FROM EMPLOYEES;
-- SELECT COUNT(ID) FROM EMPLOYEES GROUP BY DEPARTMENT;
-- SELECT DEPARTMENT, COUNT(*) AS empcount FROM EMPLOYEES GROUP BY DEPARTMENT HAVING COUNT(*) <5;
-- SELECT *FROM EMPLOYEES;

-- SELECT C.NAME, O.AMOUNT FROM CUSTOMERS C, ORDERS O WHERE  C.ID=O.ID;
-- UPDATE EMPLOYEES  SET SALARY= 2500 WHERE ID=20260;
DELETE FROM EMPLOYEES WHERE SALARY =2000;


