profile=[]
name=input("Enter your Full name: ")
profile.append(name)
email=input("Enter your email: ")
profile.append(email)
phone_number=input("Enter your phone number: ")
profile.append(phone_number)
country=input("enter your country: ")
profile.append(country)
print("Student Profile:")
print("_________________")
print("Name:", profile[0])
print("Email:", profile[1])
print("Phone Number:", profile[2])
print("Country:", profile[3])
